# name: Create Issue Every Minute

# on:
#   schedule:
#     - cron: '* * * * *'  # This will run the action every minute

# jobs:
#   create_issue:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Create GitHub Issue
#         uses: peter-evans/create-issue@v2
#         with:
#           title: 'Automated Issue - {{ github.run_id }}'
#           body: 'This issue was automatically created by GitHub Actions at {{ github.event.schedule }}.'
#           labels: 'automated'
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
