name: Auto Issue Creator

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: 'Automated Issue Title'
          content-filepath: 'issue-template.md'  # Path to your issue template
          labels: 'bug, automation'
